# Generated by Django 3.0.2 on 2020-02-02 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_auto_20200126_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnairecontent',
            name='choices',
            field=models.CharField(default='Very good, good, moderate', max_length=300),
            preserve_default=False,
        ),
    ]
