# Generated by Django 3.0.2 on 2020-02-02 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_questionnairecontent_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnairecontent',
            name='choices',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
