# Generated by Django 3.0.2 on 2020-02-02 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_auto_20200202_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnairecontent',
            name='choices',
            field=models.CharField(blank=True, default='', max_length=300),
            preserve_default=False,
        ),
    ]
