# Generated by Django 3.0.2 on 2020-02-04 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_auto_20200202_1606'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='questionnairecontent',
            name='qid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
