# Generated by Django 3.0.2 on 2020-02-06 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0008_auto_20200206_2137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionnaire',
            name='ages',
        ),
    ]
