# Generated by Django 3.0.2 on 2020-02-06 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0009_remove_questionnaire_ages'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
