# Generated by Django 3.0.2 on 2020-02-11 17:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0010_questionnaire_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='answercontent',
            name='age',
            field=models.CharField(default=10, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answercontent',
            name='date',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='questionnairecontent',
            name='qid',
            field=models.CharField(default=10, max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='QuestionAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qid', models.CharField(max_length=100)),
                ('answerType', models.CharField(max_length=100)),
                ('answer', models.CharField(max_length=1000)),
                ('answerContent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionAnswer', to='API.AnswerContent')),
            ],
        ),
    ]
