# Generated by Django 3.0.2 on 2020-03-01 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0011_auto_20200211_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionanswer',
            name='questionText',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
