# Generated by Django 3.0.2 on 2020-03-03 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0012_questionanswer_questiontext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answercontent',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
